# Generated by Django 4.0.5 on 2022-06-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
    ]
