# Generated by Django 3.1.8 on 2022-06-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_auto_20220617_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
