# Generated by Django 3.1.8 on 2022-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_delete_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='add_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='expired_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
