# Generated by Django 3.1.8 on 2022-06-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_auto_20220618_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='add_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='history',
            name='expired_quantity',
        ),
        migrations.RemoveField(
            model_name='history',
            name='inventory_quantity',
        ),
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.IntegerField(choices=[(0, 'add_quantity'), (1, 'expired_quantity'), (2, 'inventory_quantity')], default=0),
        ),
    ]
