# Generated by Django 3.1.8 on 2022-06-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0004_category1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category1',
            new_name='Categorya',
        ),
    ]
