# Generated by Django 3.1.8 on 2022-06-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0005_auto_20220619_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorya',
        ),
    ]
